backend:
  name: github
  repo: rogermparent/tubes

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: src/pages/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: category, label: Category }
      - { name: tags, label: Tags, widget: list }
      - name: author
        label: Author
        widget: relation
        collection: authors,
        searchFields: ["name", "slug"]
        valueField: "slug"
        displayFields: ["name"]
      - { name: body, label: Body, widget: markdown }
  - name: videos
    label: Videos
    label_singular: video
    folder: src/pages/videos
    create: true
    fields:
      - { name: title, label: Title }
      - { name: thumbnail, label: "Thumbnail", widget: image }
      - { name: link, label: "Magnet Link" }
      - { name: length, label: Length }
      - { name: upload_time, label: "Upload Time", widget: date }
      - { name: channel, label: "Channel" }
      - { name: body, label: "Description", widget: markdown }
